# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TensorFlow Technical Notes
email: volease@gmail.com
description: 我们不生产Tensor,我们只是大自然的搬运工
# this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  liaha

# Build settings
markdown: redcarpet
highlighter: rouge

kramdown:
  input: GFM

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

gems:
  - jekyll_figure

figures:
  dir: /assets
  enumerate: true
